INSERT INTO Songs (Author, Genre, Rating, Title, Year) 
VALUES 
('Blue Swede', 'Pop', '5', 'Hooked on a Feeling', '2002'),
('Raspberries', 'Classic Rock', '4.9', 'Go All the Way', '2011'),
('Norman Greenbaum', 'Soft Rock', '4.9', 'Spirit in the Sky', '2006'),
('David Bowie', 'AOR', '4.4', 'Moonage Daydream', '2012'),
('Elvin Bishop', 'Pop Rock', '4.2', 'Fooled Around and Fell in Love', '2010'),
('10cc', 'Punk', '4.1', 'I am Notin Love', '2003'),
('The Jackson 5', 'Pop', '4.5', 'I Want You Back', '2004'),
('Redbone', 'Classic Rock', '4.2', 'Come and Get Your Love', '2008'),
('The Runaways', 'Soft Rock', '4.9', 'Cherry Bomb', '2002'),
('Rupert Holmes', 'AOR', '4.3', 'Escape (The Piña Colada Song)', '2002'),
('Five Stairsteps', 'Pop Rock', '4.9', 'O-o-h Child', '2011'),
('Marvin Gaye and Tammi Terrell', 'Punk', '4.5', 'Aint No Mountain High Enough', '2010'),
('Electric Light Orchestra', 'Pop', '4.5', 'Mr. Blue Sky', '2011'),
('Sweet', 'Classic Rock', '4.25', 'Fox on the Run', '2008'),
('Aliotta Haynes Jeremiah', 'Soft Rock', '4.1', 'Lake Shore Drive', '2009'),
('Fleetwood Mac', 'AOR', '4.4', 'The Chain', '2014'),
('Sam Cooke', 'Pop Rock', '4.4', 'Bring It On Home to Me', '2005'),
('Glen Campbell', 'Punk', '5', 'Southern Nights', '2007'),
('George Harrison', 'Pop', '4.4', 'My Sweet Lord', '2009'),
('Looking Glass', 'Classic Rock', '4.6', 'Brandy (You are a Fine Girl)', '2013'),
('Jay and the Americans', 'Soft Rock', '4.2', 'Come a Little Bit Closer', '2010'),
('Silver', 'AOR', '4.5', 'Wham Bam Shang-A-Lang', '2014'),
('Cheap Trick', 'Pop Rock', '5', 'Surrender', '2007'),
('Cat Stevens', 'Punk', '4.9', 'Father and Son', '2002'),
('Parliament', 'Pop', '4.5', 'Flash Light', '2014'),
('The Sneepers featuring David Hasselhoff', 'Classic Rock', '4.6', 'Guardians Inferno', '2011');